apiVersion: v1
kind: Service
metadata:
  name: blockchain-server
  namespace: blockchain
  labels:
    app: blockchain-server
spec:
  selector:
    app: blockchain-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

